// <auto-generated />
using Kerko.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kerko.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250325105104_indexEmerMbiemer")]
    partial class indexEmerMbiemer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Kerko.Models.Patronazhist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Atesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Census2013Preferenca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Census2013Siguria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datelindja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emigrant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISigurte")
                        .HasColumnType("TEXT");

                    b.Property<string>("KodBanese")
                        .HasColumnType("TEXT");

                    b.Property<string>("Koment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kompania")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListaNr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronazhisti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferenca")
                        .HasColumnType("TEXT");

                    b.Property<string>("QV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendlindja")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Patronazhist");
                });

            modelBuilder.Entity("Kerko.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Atesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datelindja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emer")
                        .HasColumnType("TEXT");

                    b.Property<string>("GjendjeCivile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kombesia")
                        .HasColumnType("TEXT");

                    b.Property<string>("LidhjaMeKryefamiljarin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemer")
                        .HasColumnType("TEXT");

                    b.Property<string>("NrBaneses")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qyteti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seksi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendlindja")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Emer");

                    b.HasIndex("Mbiemer");

                    b.HasIndex("Mbiemer", "Emer");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Kerko.Models.Rrogat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DRT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIPT")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PagaBruto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profesioni")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Rrogat");
                });

            modelBuilder.Entity("Kerko.Models.Targat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modeli")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ngjyra")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumriTarges")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("NumriTarges");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Targat");
                });
#pragma warning restore 612, 618
        }
    }
}
