// <auto-generated />
using System;
using Kerko.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kerko.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kerko.Models.Patronazhist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Atesi")
                        .HasColumnType("text");

                    b.Property<string>("Census2013Preferenca")
                        .HasColumnType("text");

                    b.Property<string>("Census2013Siguria")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Datelindja")
                        .HasColumnType("text");

                    b.Property<string>("Emigrant")
                        .HasColumnType("text");

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("ISigurte")
                        .HasColumnType("text");

                    b.Property<string>("KodBanese")
                        .HasColumnType("text");

                    b.Property<string>("Koment")
                        .HasColumnType("text");

                    b.Property<string>("Kompania")
                        .HasColumnType("text");

                    b.Property<string>("ListaNr")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("text");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("text");

                    b.Property<string>("Patronazhisti")
                        .HasColumnType("text");

                    b.Property<string>("Preferenca")
                        .HasColumnType("text");

                    b.Property<string>("QV")
                        .HasColumnType("text");

                    b.Property<string>("Tel")
                        .HasColumnType("text");

                    b.Property<string>("Vendlindja")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Patronazhist");
                });

            modelBuilder.Entity("Kerko.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("text");

                    b.Property<string>("Amesi")
                        .HasColumnType("text");

                    b.Property<string>("Atesi")
                        .HasColumnType("text");

                    b.Property<string>("Datelindja")
                        .HasColumnType("text");

                    b.Property<string>("Emer")
                        .HasColumnType("text");

                    b.Property<string>("GjendjeCivile")
                        .HasColumnType("text");

                    b.Property<string>("Kombesia")
                        .HasColumnType("text");

                    b.Property<string>("LidhjaMeKryefamiljarin")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemer")
                        .HasColumnType("text");

                    b.Property<string>("NrBaneses")
                        .HasColumnType("text");

                    b.Property<string>("Qyteti")
                        .HasColumnType("text");

                    b.Property<string>("Seksi")
                        .HasColumnType("text");

                    b.Property<string>("Vendlindja")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Emer");

                    b.HasIndex("Mbiemer");

                    b.HasIndex("Mbiemer", "Emer");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Kerko.Models.Rrogat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DRT")
                        .HasColumnType("text");

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("Kategoria")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("text");

                    b.Property<string>("NIPT")
                        .HasColumnType("text");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("text");

                    b.Property<int?>("PagaBruto")
                        .HasColumnType("integer");

                    b.Property<string>("Profesioni")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Rrogat");
                });

            modelBuilder.Entity("Kerko.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchParams")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("Timestamp");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("Kerko.Models.Targat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Emri")
                        .HasColumnType("text");

                    b.Property<string>("Marka")
                        .HasColumnType("text");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("text");

                    b.Property<string>("Modeli")
                        .HasColumnType("text");

                    b.Property<string>("Ngjyra")
                        .HasColumnType("text");

                    b.Property<string>("NumriPersonal")
                        .HasColumnType("text");

                    b.Property<string>("NumriTarges")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Emri");

                    b.HasIndex("Mbiemri");

                    b.HasIndex("NumriTarges");

                    b.HasIndex("Mbiemri", "Emri");

                    b.ToTable("Targat");
                });
#pragma warning restore 612, 618
        }
    }
}
